### ISSUE TITLE
Add Feedback button

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#10]
Add a Feedback button that would create an Issue on GitHub (dina-planning repo) with pre-selected Label.

**Comment by hacole01** [comment]
button seems to function from all pages I tested BUT
- would be much more user friendly if the page either opened in a new window OR returned user to the previous DINA window they were in before the selected the 'feedback' button(once you submit the 'feedback' the only way I see to get back to where I was working is to use the browser 'back' button, which pushes back through the 'new issue' page also.

**Comment by cgendreau** [comment]
Ready to be validated.

**Comment by hacole01** [comment]
tested button from several different pages, each time a new window was opened to report. So that is great. My only other note is that it might be useful to communicate that is what happens, as some users might be worries to 'loose their spot' . Maybe a hover/pop up that says 'opens in new window' or text on the page that indicates that. Isn't vital, but would be more user-friendly.
