### ISSUE TITLE
Collecting Event: Add ability to choose a person from Agent to correspond to the georeferenced by

### ISSUE THREAD

**Issue by dshorthouse** [AAFC-BICoE/dina-planning#127]
GIVEN I have accessed DINA as a georeferencer

WHEN I add a new georeference

THEN I expect to be able to type a verbatim "Geoferenced By" and to secondarily choose a person from the Agent module

AND [describe additional action(s) from the system]

**Comment by TravisGobeil** [comment]
So you have requested accommodation of two scenarios: 

1. A Verbatim Georeferencing Agent 
2. Linking to a Known Agent to "Georeferenced by" from the Agents Module. 

Can you help me understand the use of "verbatim" in this context. I have Verbatim Coordinates fields already, which I could associate with an agent (call it "Verbatim Coordinates by") but I feel this is unnecessary complication. To me this "verbatim georeferenced by" is simply an "Unknown Agent" (a basic text string).

If rephrased as these two scenarios, does it still make sense to you:

1. "Unknown Agent" - I do not know the Agent so I am simply going to put the text string I have, and it will not be linked.
2. "Known Agent" - I know the Agent and can simply start typing the name, pick it from the list, and move on.

**Comment by dshorthouse** [comment]
`Georeferenced By` could be a software "Agent" just as it could be a Person. "Known Agent" presupposes there is a Person entry in Agent for instances where `Georeferenced By` is a human & the user additionally knows who it is (i.e. disambiguates on-the-fly). In principle, this is the same design paradigm as optionally picking a Person from Agent within Collecting Event to disambiguate a collector from verbatim collector(s). The use-case here is to find all actions a Person (not a user or an ambiguous agent string) has executed throughout all of DINA regardless of context.

**Comment by TravisGobeil** [comment]
My initial answer to your question is 'Yes'. If I search for "Michael Smith" matches in the "Georeferenced by" field, I would want all matching data - both KNOWN and UNKNOWN agents, sorted as such. 

When entering the data, if I do not know if this is a specific Michael Smith, I simply enter the text string. I don't need to flag that I don't know this agent, since the lack of a link to a specific agent tells me that I am dealing with an Unknown Agent, and I should be able to search for that string at any point.

You can always go back and update any field, and attribute it to a Known Agent, once you know. In fact, being able to isolate entries based on matches of Unknown Agent strings would allow me to better isolate bad data and correct it, would it not? It's easy to accommodate in this scenario. 

Example: I search for the string "Michael Smith" in only the Georeferenced by field: 

#### Search Results: `110` Records Found matching `Michael Smith` from `Georeferenced by`
- 7 Records attributed to [Michael Smith ID: 1038](url)
- 70 Records attributed to [Michael Smith ID: 2229](url)
- 33 Records attributed to [Unknown Agent "Michael Smith"](url)

**Comment by dshorthouse** [comment]
I *think* we're on the same page here, but `Georeferenced By` could be a string representing more than one person (when it's a person). If what you vision can accommodate this then we're a-ok.

**Comment by dshorthouse** [comment]
Somewhere on other tickets, I've tried to suggest some standard language and terminology with respect to Agent, People, and agent string, but I'll briefly recap here hoping it might help convey more precision in our dialogue. It's easy to lose sight of meaning and context.

Agent: the module, capital 'A'
Person: a definitive, canonical representation of a human in the Agent module, capital 'P'
agent string: verbatim representation purported to represent a human but whose identity requires disambiguation through just-in-time linking or some future disambiguation routine, lowercase 'a' always with the 'string' qualifier

Example:
"Mr. and Mrs. John Smith" the agent string in `Georeferenced By` can be linked to John Smith the Person and Mary Smith the Person in the Agent module.

**Comment by cgendreau** [comment]
I created the glossary: https://github.com/AAFC-BICoE/dina-planning/blob/master/docs/glossary.md

I would not include capital/lowercase there but it's a good place for general definitions.
