### ISSUE TITLE
Add title and appellation to agent person

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#128]
Another iteration on agent person fields.

Based on https://github.com/AAFC-BICoE/dina-planning/issues/98#issuecomment-766814121

This ticket will focus on the following fields with the associated tooltip:

`appellation`: Prefixing a person's name e.g.: Mr, Mrs, Miss, Ms, Mx, Sir
`title`: Academic/professional title(s) prefixing a person's e.g.: Dr., Prof.

cc @dshorthouse

**Comment by dshorthouse** [comment]
Although #98 is quite exhaustive, we still need to decide if some of these, which imply demographics & gender or are temporal in nature (i.e. John Smith's Ph.D. was not yet conferred, Mary was once Mark) are actually necessary to express identity. Or, is it sufficient to include all these accoutrements in running lists of known & unstructured aliases? The purpose of these is to merely assist with search and on-the-fly disambiguation. In that respect, all the additional fields beyond `name` for a person in Agent incur a maintenance burden. So, we have to ask, under what conditions/scenarios is having eg "Mrs." necessary in the canonical set of fields for a person vs. merely included in an unstructured alias?

Here's an example:

Collected By: "Mr. & Mrs. John Smith"
Person in Agent: "John Smith", with alias "Mr. John Smith"
Person in Agent: "Mary Smith", with aliases "Mrs. John Smith", "Mrs. Mary Smith"

Because it requires significant, secondary effort to uncover who is/was the "Mrs" in "Mrs. John Smith", it may be some time before we ever have an entry in Agent for "Mary Smith". We would not make one as a placeholder because she may remain unknown in the verbatim collectors entry.

**Comment by cgendreau** [comment]
The work for that is done, should it be merged or put on hold?

**Comment by dshorthouse** [comment]
Sorry, I realize my comment now seems like a regression. I fear we might be baking-in rigidity when none is required. What I believe is more fruitful is to retain nothing more than `name` (`given` and `family` is fine too) but to build the aliases to accommodate all the varied representations of names that people have. The *actual* need is to facilitate the on-the-fly disambiguation choices a user must make when linking a person to a verbatim entry. And so, search for a person additionally uses and presents those aliases within the drop-down as visual cues.

**Comment by cgendreau** [comment]
We can also simply not merge it to avoid confusion and instead move to aliases.

**Comment by cgendreau** [comment]
For a first version of alias would we need more than a list of "names" that are alternative name strings?

**Comment by dshorthouse** [comment]
In the same comment on #98, I'd go with a text or jsonb with language keys & flat arrays to accommodate the eventual need for multiple, alternate representations in other languages:

```
{ en: [ "Mrs. Jack Smith", "Donna Smith", "D. Smith" ]}
```

Imposing any additional structure on any of these gets us into the same mess of having multiple fields that could experience considerable flux and/or can be context-specific. If you envisioned aliases as self-referential parent/child, that I believe would be far too complex and would blur the lines of unique identity for each entry.

**Comment by dshorthouse** [comment]
> We can also simply not merge it to avoid confusion and instead move to aliases.

Fair point. No sense kicking the confusion down the road. Best leave as a branch then and move on to aliases w/ requirement to make these viewable/editable within Agent as well as viewable/searchable in drop-down wherever used in context such as Collecting Event while "choosing" a person to link.

**Comment by cgendreau** [comment]
Not sure the language can be mandatory since it may not always be known.

I will close this ticket and open a new one for aliases so we can start to document requirements.

**Comment by cgendreau** [comment]
Actually it already exists https://github.com/AAFC-BICoE/dina-planning/issues/97

**Comment by dshorthouse** [comment]
> Not sure the language can be mandatory since it may not always be known.

Agree. Judging by what's happening in Wikidata where the whole platform is meant to be agnostic to any one language, most of the aliases created for people items reside under English, eg [Marie-Victorin](https://www.wikidata.org/wiki/Q2596174). However, when there is a need to represent a name in another language, there's at least a home for it.

**Comment by cgendreau** [comment]
I created a new ticket (#131) since the old one was going in all directions.
