### ISSUE TITLE
Find Current Place Name from lat long

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#161]
GIVEN I have accessed DINA as a dina user

WHEN I have decimal lat/long (from the label)

THEN the system should allow me to use that to find the Current Place Name

AND I can confirm the Current Place Name matching the lat/long

**Comment by heathercole** [comment]
@cgendreau not sure the relevant issue to document this use-case issue

please let me know if should go somewhere else, i can move it.

Relating to the functionality that is being developed with place names, i think it is vital that 'artificial' places names are not imported into the data management system. The example at one of the meetings showed an unstructured text string that included "Ottawa" several times. This would be impossible for managers to "manage" and badly clutter data exports.

related to that, @banchinic has also indicated an issue, where a place-name association can also add "wrong" data, in some of the use-cases presented thus far:

"Because if I use the service right now for a soil sample that was taken by the side of Ramsay Lake, the service gives me the closest road (see included jpeg named OpenStreetMap). However, when I put my coordinates in GoogleEarth they give me the exact location I was at (see included jpeg GoogleEarth). 

So this is the string that it gives me in DINA: Eardley Road, La Pêche, Les Collines-de-l'Outaouais, Outaouais, Quebec, Canada.

This is not just imprecise it’s wrong! If I can’t change it for the lake I don’t like adding that information to a record…
![image](https://user-images.githubusercontent.com/50373105/114219663-f3a7a280-9938-11eb-814c-87cb60383393.png)
![image](https://user-images.githubusercontent.com/50373105/114219719-08843600-9939-11eb-93df-21d734c664a6.png)

**Comment by cgendreau** [comment]
I don't think it is wrong.
You are comparing 2 different things, on OpenStreetMap you are asking for the closest Place based on lat/long, the road is quite close and I would expect the lake to be in that list.

On GoogleEarth you just plot the coordinates, this is what View on Map is doing.

**Comment by cgendreau** [comment]
unless the issue is that the lake is not in the list? If it's the case could you just provide the coordinates you are using?

**Comment by banchinic** [comment]
> unless the issue is that the lake is not in the list? If it's the case could you just provide the coordinates you are using?

Hi Christian! No the lake doesn't seem to be a choice. I don't have a list of places to pick I only see one (the road). See attached screenshot in DINA with the coordinates. 
![LakeRamsay](https://user-images.githubusercontent.com/72508742/114224101-a3334380-993e-11eb-9098-91c9dd36a340.jpg)

**Comment by banchinic** [comment]
> unless the issue is that the lake is not in the list? If it's the case could you just provide the coordinates you are using?

No I don't seem to have a choice of places to pick. I only see one (the road). See attached screenshot with coordinates. 
![LakeRamsay](https://user-images.githubusercontent.com/72508742/114224306-eab9cf80-993e-11eb-9c5c-38d29a280e1c.jpg)

**Comment by cgendreau** [comment]
I will have a look I'm not sure if the lsit always has a single element when you search by lat/long. But, is all cases you can change the test in the Search box and get the lake.

If you search for "lake ramsay, quebec" you will get 
https://www.openstreetmap.org/way/38854426

**Comment by heathercole** [comment]
in this case, why would the user use the tool at all? Instead of just entering Quebec/Canada manually. Will be good to review how this functionality comes together when the related data fields are available on the form. cheers.

**Comment by cgendreau** [comment]
Just entering Quebec/Canada manually will not give you what we need to have translations and do proper data sharing.
