### ISSUE TITLE
Material Sample Type - will edit be available?

### ISSUE THREAD

**Issue by rintoult** [AAFC-BICoE/dina-planning#206]
GIVEN I have accessed DINA as collection manager

WHEN I make a mistake entering a material sample type

THEN shouldn't I be able to edit it

AND resave?

**Comment by cgendreau** [comment]
Probably not short term. Material Sample Type is what can guide you once the material sample is created. Changing it has major impact since we could not guarantee the integrity of a workflow. For example you have a molecular sample, you do sequencing on it and then you change the type to Whole Specimen.

If a mistake happened it is always possible to recreate them. Material Sample type is usually set but a Split workflow so in theory, in your case, you never need to touch it.
