### ISSUE TITLE
Streamline creating multiple Collection Methods

### ISSUE THREAD

**Issue by michellelocke** [AAFC-BICoE/dina-planning#234]
If a user wishes to create more than one Collection Method they must create the first, save it, go from the newly created record back to the list page, then hit Create New. It would be much more streamlined to be able to create a new Collection Method right from an individual Collection Method record. This save the step of having to go to the list page. It would be great to create a new Method from either the list page or an individual record page.

**Comment by dshorthouse** [comment]
@michellelocke Might this be an artifact of having too few records in the system, none yet migrated from source? How often in the CNC database do you need to create new Collection Methods?

**Comment by michellelocke** [comment]
@dshorthouse yes, likely it wouldn't be so frustrating once these fields are populated with our base lists. However, if I do need to add multiple (and I have in the past, especially with mass digitization and you find pockets of specimens that require these types of values to be added) I would like it to be more streamlined. I only added a few in this test instance and was frustrated to have to make those extra steps. It would just make it a nice experience for us all not to have to go back to the main list each time.

**Comment by dshorthouse** [comment]
Understood. At present, Collection Method is a pick list with a fixed controlled vocabulary that only the collection manager role has permission to set. The motivation here is to keep the list "clean", unlike freeform fields in some instances (eg collectors) where unique values from past entries are presented in what superficially appears like a pick list to help facilitate data entry. But, those alternative freeform fields will require typing as the number of unique values become quite numerous. Pick list fields like Collection Method are not expected to be extremely large.

What we'd have to safeguard against with "add to fixed pick list on-the-fly" is a ballooning of spurious values because it may seem easier to add a new one than to go fishing for one that already exists. Clearly, role = Collection Manager must still be invoked.

<img width="327" alt="Screen Shot 2021-11-01 at 11 43 46 AM" src="https://user-images.githubusercontent.com/326459/139701328-2301ebf9-b678-4889-8cba-96715b1297b0.png">

**Comment by michellelocke** [comment]
I never explicitly suggested that it be open to all for editing. I do not think the picklists should (as they are not in CNCDB currently) . I agree that they should be confined to the collections managers role. I try to use more generic terms like "user" to explain my ideas, questions, problems, rather than say "I" want something to be done a certain way. Please don't read more into it and ask for clarity if you aren't certain if I mean all users or a subset of users.

**Comment by dshorthouse** [comment]
Actually, I missed the fact that you had written "user" in the ticket. My assumption is that such lists are controlled by collection managers. What I meant is that even with the Collection Manager role, there will be a temptation to add new terms when it's not obvious when a term might already exist. That's not a problem when a list is small but it becomes increasingly hard to manage when lists surpass a tipping point...it tends to get larger because it seems easier to add a new term than to hunt & peck for an existing one.

**Comment by michellelocke** [comment]
I do not find that to be the case in our current database. The few administrators are very careful about what terms we add and only add them when they are truly needed. Yet, on occasion, I still find we are missing terms that are truly unique. None of our lists have ballooned out in the seven years that CNCDB has been in operation. 

I would never expect terms be added to a dropdown list during data entry but want a more streamlined way for me to add multiple terms to the list from the list itself in the way described in my original post. I am just looking for a way to reduce the number of clicks and pages you visit if you need multiple entries.

**Comment by dshorthouse** [comment]
Understood. I see 152 unique values for Collection Method in the CNC database. See also #247 for relevance. Ordinarily, there'd be something like a modal dialog for this. Hopefully there's a WCAG-compliant solution for this.

**Comment by cgendreau** [comment]
This will be done by API as part of the data migration. No plan for that in the ui.
