### ISSUE TITLE
Display Collection Number instead of the unique DB identifier in Collecting Event view

### ISSUE THREAD

**Issue by banchinic** [AAFC-BICoE/dina-planning#331]
We've talked about this before but I just wanted to record it as the change hasn't been made yet. 
Can we have the collection number displayed in big? And like we said before remove the DB generated unique number (or at least make it smaller?). It doesn't mean anything to us and really isn't helpful.
In the tab we would see the collection number also instead of the generated number. 
![CollEvent](https://user-images.githubusercontent.com/72508742/174076030-7fbe8b63-6eb8-4a07-9607-a469b558e1e5.jpg)

**Comment by cgendreau** [comment]
Actually the main identifier is Collector's Number (and not Collection Numbers). It was under Collecting Agent (by mistake) so we moved it to a new Identifier section. This is already deployed. Next, we will use the Collector's Number to do this ticket.

**Comment by banchinic** [comment]
isn't Collector's Number the ID of the person who collected the sample? For us that is not relevant for the main ID at all. Most of our samples are collected by the same person so if they are sorted by Collector's Number I will just get all the samples that were collected from our lab. We were planning to use Collection Number for our 4 digit number that is unique to every Collecting Event (the number changes everytime we sample a different site).

**Comment by cgendreau** [comment]
The definition (see tooltip) is "An identifier given to the collecting-event at the time it was recorded." The ID of the person, if we have such thing, would go in the collectors (verbatim).

**Comment by banchinic** [comment]
ok then yes I can use this but I am almost certain that the herbarium needed a Collector's number to identify the person collecting the samples (differentiate between people with the same name). Maybe this should be verified with them.

**Comment by cgendreau** [comment]
Yes, that's possible. It is actually quite confusing and some definitions are incomplete or missing.

https://aafc-bicoe.github.io/dina-documentation/#collection_numbers
That's a start but it's not even in the application. We will need to review that again.

@dshorthouse @jmacklin ?

**Comment by jmacklin** [comment]
Agree that this can be confusing! A collector's number is traditionally assigned by the collector at the time of sampling. So, for example, my collecting "numbers" (actually alphanumeric) are JAM-2022-137 but everyone does this differently. The key is that this is an "identifier" given by the collector. In some cases especially in zoology, there can be a number/identifier associated to the collecting event by the collector(s). This is used when many collectors share the same event data. Claudia, I think you were referring to a unique identifier that is associated with the collectors themselves to help with disambiguation. These do exist in various systems and are often hidden. A more modern good example are ORCIDS. These identifiers associated with a collector's name string and its variants (i.e., James Macklin, James A Macklin, J. Macklin, etc.) are present in DINA in the agents module. However, these are not relevant to this particular discussion.

So, perhaps it is the tool tip definition that is causing issues? I think it is confusing to tie the collector number directly to an event as one event (especially in zoology) can have many collections/samples done under it.

How about "An identifier assigned by the collector(s) at the time it was sampled"...?

**Comment by banchinic** [comment]
OK @jmacklin that makes sense. I am assuming then that we would use the collector's number field if the definition is "An identifier assigned by the collector(s) at the time it was sampled" but it's confusing for me because we always only have one number related to one event. 

Anyways, I don't really care what it's called but there should definitely be a primary ID under the Collecting Event page (if it is not left blank), it should be what is displayed on top of the page and then every collection can use it the way they want. In our case it's a four digit number (when it's collected by us and not from an external collection) that is tied to that particular sampling place at that particular time. 

Also, what is Collection Number then?

**Comment by dshorthouse** [comment]
All good points. Will also add that UUIDs are ugly things & humans should never have to look at them. Besides deciding *what* should be shown as the title of a collecting event (it'll varies by domain), I advocate for de-emphasizing the presentation of UUIDs in all cases. If there's no usable title, well...there's no usable title; the UUID need not be the default substitute. It can still be shown, just not so much in your face.

**Comment by dshorthouse** [comment]
> OK @jmacklin that makes sense. I am assuming then that we would use the collector's number field if the definition is "An identifier assigned by the collector(s) at the time it was sampled" but it's confusing for me because we always only have one number related to one event.

There's a swirl of possibilities here, largely because different groups of biologists who collect different taxa think of the concept of a collecting event very differently. For botanists, the collecting event is intimate with the herbarium sheet: one plant, one collecting event (Aside: I suspect this reductionism is mostly an artefact of software design in collections management systems). A collector number in botany is often an incrementing alpha numeric "number" that typically indicates a run of temporally sequential specimens collected over a season & so it's more about the occurrence than it is about the event. As always though, "it depends". Whatever the motivation, the number does not serve to indicate the identity of a person; it's more like a ledger of their activity. For entomologists: there could be one collecting event & tens of thousands of specimens, each with their own label that each indicate exactly the same date/locality. Or, there may be a single collecting event for a single specimen if it was collected by hand. As near as I can tell, various Darwin Core terms have emerged to accommodate the range of possibilities.
 
### Darwin Core terms about the Event

`eventID`: An identifier for the set of information associated with an Event (something that occurs at a place and time). May be a global unique identifier or an identifier specific to the data set.

`fieldNumber`: An identifier given to the event in the field. Often serves as a link between field notes and the Event.

### Darwin Core terms about the Occurrence

`recordNumber`: An identifier given to the Occurrence at the time it was recorded. Often serves as a link between field notes and an Occurrence record, such as a specimen collector's number.

> Anyways, I don't really care what it's called but there should definitely be a primary ID under the Collecting Event page (if it is not left blank), it should be what is displayed on top of the page and then every collection can use it the way they want. In our case it's a four digit number (when it's collected by us and not from an external collection) that is tied to that particular sampling place at that particular time.
> 
> Also, what is Collection Number then?

I think it depends who assigns the number & for what purpose. The UUID assigned by DINA for a collecting event is probably best interpreted as an `eventID` because it's an opaque number for a "set of information associated with an Event" & it's globally unique.

It sounds like `fieldNumber` defined above is closest to @banchinic use of a 4-digit number if we relax our instinct to think of the word "field" as "out in the sun" or of a particular parcel of land. The intent of our "Collection Number" in DINA is aligned with this `fieldNumber` as well - a number a biologist assigns at the time they collected one or more samples that indicates - to them - the intersection of place & time, nothing more. Typically, collector's number(s) of the kind James gave examples of get stuffed in `recordNumber`.

**Comment by banchinic** [comment]
> It sounds like `fieldNumber` defined above is closest to @banchinic use of a 4-digit number if we relax our instinct to think of the word "field" as "out in the sun" or of a particular parcel of land. The intent of our "Collection Number" in DINA is aligned with this `fieldNumber` as well - a number a biologist assigns at the time they collected one or more samples that indicates - to them - the intersection of place & time, nothing more. Typically, collector's number(s) of the kind James gave examples of get stuffed in `recordNumber`.

I just want to clarify that for us it's a bit like entomology and one collecting event is actually one soil sample. If we take another soil sample 10 meters away, we will use the next collecting event number for that one. I can have a lot of different specimens linked to the same collecting event. It is absolutely imperative though that I can easily find out that they all come from the same one and the same original soil sample that was collected (and why I needed to have the link to the specimens linked on the collecting event page). 

As long as I know where to put that number (which field in DINA), that I can have that field displayed as my Collecting Event Identifier prominently at the top of the page and that I can search for this number I'm good.

**Comment by cgendreau** [comment]
ok, indeed the problem is with the definitions. I will update them.

**Comment by cgendreau** [comment]
Changes are now in the user guide: https://aafc-bicoe.github.io/dina-documentation/#collection_numbers

**Comment by cgendreau** [comment]
So,` Collector's Number` is back were it used to be and `Collection Number` is the field that should be used for the use case here.
