### ISSUE TITLE
Support group of collectors

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#65]
GIVEN I have accessed DINA as collection manager (restricted to ?)

WHEN I click Collector Group (group, team ? not sure what is the best word) from the menu

THEN the system allows me to create a group of collector with a name and multiple agents where the order is preserved

AND I can save the group of collectors and refer to it in collecting event

cc @michellelocke @shannonasencio @hacole01

**Comment by heathercole** [comment]
Please note that the ORDER of the members listed is important, and that if the ORDER is different, then it is a different group. Similarly, the groups do not change members. 3 people listed as collectors for an object in 1999 is a completely different group than 2 of them collecting an object at any time. The 3 same people listed in different order must be maintained as a different group. @michellelocke  (any conflicts with that statement for CNC data? I think that even if CNC doesn't "care" structuring it that way is not an issue? -thanks

**Comment by cgendreau** [comment]
The first version of that feature is available. Note that Collector Group are currently editable but they should not.

**Comment by cgendreau** [comment]
They are not editable so ready for feedback.

**Comment by heathercole** [comment]
happy to test, but not clear where to look, or how this does (or does not) relate to the agents section in the media module. 
My first questions are whether groups are their own objects, or whether they are a build of existing agents. (eg. how to edit if there is a typo in a name spelling?)

**Comment by michellelocke** [comment]
@heathercole I don't see an issue with what is proposed in terms of structuring a collector group. For us, order is not generally something that has much meaning (we don't have a primary collector) but we would still want to preserve the order as is on the labels. 

I do have concern about not being able to edit a collector group once it is created. It is not something that will need to be done regularly but I find that everything in a database needs to be editable as there always ends up being a reason to need to edit. Even if the edit function is only available for collections managers, it should be editable. An instance might occur if I select I.A. Scott, but it should have been I.M. Scott. If both were valid agents, then going to edit the Agents table does not fix the problem. If this cannot be edited, then my only option is to delete it and recreate the group. I would much prefer to edit it.

**Comment by shannonasencio** [comment]
I have to agree with @michellelocke. I think there should certainly be limitations on WHO can edit records/groups/etc. in the database via permissions, but not on WHAT can be edited. If records/groups/etc. cannot be edited, it leads to proliferation of records/groups/etc. and a bunch of "junk" records/groups/etc.

Also agree with @heathercole that order is important for herbarium collections as collector numbers are typically on labels and are associated to the first collector listed.

**Comment by michellelocke** [comment]
I just had a quick peak and I'm not sure I like how Collector Group is implemented. Having a name for the group is not very useful. I'm fairly certain we would all want our "group name" to be the actual collectors, that is, exactly what is on the labels. So if my label says M.M. Locke, O. Lonsdale & J.H. Skevington then I want to search for my group using exactly that (M.M. Locke, O. Lonsdale & J.H. Skevington). A name adds an extra layer of complexity that is not useful. I only want to know who the group is made up of.

I realize that I could name the group the same thing as the list of agents but it seems like that could lead to spelling mistakes.

There seem to be some other issues, which I will write here but may need to be split into their own issues.

The collector/collector group fields should look the same as they are on the label. I would generally be tagged in the collector field as M.M. Locke, but possibly as M. Locke, and almost never as Michelle Locke. These will all have to be different agents and will all need to link together (as well as all of the groups I am a part of) so that if someone searches for M.M. Locke in the collector, they should be able to see the results for exactly M.M. Locke or M.M. Locke plus other related agents (and any or exact type of search)

If the label says M.M. Locke, O. Lonsdale & J.H. Skevington then that is what the collector field should look like, not several names in boxes, linked to the agent table.

I have labels that say B. Gill, H. & A. Howden. This would need to show exactly as is in the Collector Group (therefore B. Gill, H. Howden & A. Howden is not acceptable).

In the implementation of Collector Group in the Collection Event (maybe getting a little far ahead but still relevant), it would be preferable to only have one list to reference for Collector. If I start typing M.M. Locke then I should Find M.M. Locke; M.M. Locke & J.H. Skevington; M.M. Locke, O. Lonsdale & J.H. Skevington, etc. We don't want to have to search two lists.

If I add the Collector Group A-Team to the Collector, I am then able to delete certain members of the Collector Group from the Collector field. There are 4 members of the A-Team auto-populated into the Collector field but I can then delete Christian and therefore it is no longer the A-Team in the Collector field. I assume this won't stay that way. But also, how does this affect searching? Further on, will A-Team be a valid search term in the Collector Field? If one person was deleted, does A-Team still search for that record, as it is not the A-Team any longer but the A-Team was still used to populated it.

Setting up the Collector and Collector Group this way is quite complicated!

**Comment by cgendreau** [comment]
> If the label says M.M. Locke, O. Lonsdale & J.H. Skevington then that is what the collector field should look like, not several names in boxes, linked to the agent table.

That would be the verbatim value (currently missing), you still need to have links to real agent.

So currently the Collector Group is simply a mechanism to autofill the Collectors. If the **only** way to have more than 1 collectors should be by using Collector Group, we will change it accordingly.

**Comment by heathercole** [comment]
I think it would be good to have a standard structure used by all collections, I would suggest that groups names focus on family/last names, leaving the particulars with initials to the individual/agent record in a group. So a search on Locke would result in 
Locke, M.M. (individual)
Locke & Skevington (group)
Locke, Lonsdale & Skevington (group)
AND
Lonsdale, Locke & Skevington.
(if more info is needed, it can be accessed by looking at the full agent names listed for the group.)

This relates to whether the query is query-ing the group name, or the agents within, i think should probably be on the agent?

Though as Michelle notes, managing agent 'synonyms' is relevant here too, I believe that at the moment, Locke, Michelle would be a different "agent" than Locke, M.M. ?? would be good to have an idea of the intended end-point for managing that functionality.

**Comment by heathercole** [comment]
OR, as noted above, if CNC has the requirement of initials, that could be accommodated in the current system, assuming the agent names are entered as relevant.

@cgendreau  I think the current implementation is a good start, I will discuss this more in-depth with the managers, but can you clarify as to whether the system will support agent "aliases"? also, can you clarify what a data export would be if there is a group of collectors. In Specify, this is an issue, as the group name is exported, not the members, which can be an issue for a data export (depending on the naming convention). With those pieces of info, I think we can structure collection requirements effectively.

**Comment by cgendreau** [comment]
Yes agent will have support for "aliases" eventually (in approx. 2 sprints).

As for the export, currently, the collectors (members) would be exported as agent.

**Comment by dshorthouse** [comment]
There's a lot going on here and indeed, there is a lot more that is not covered. For example, there will be expeditions & other "groups" whose membership is unspecified (eg `Mrs. Smith's Grade 4 Class`, `The Lewis and Clark Expedition`) but that clearly have a "title".

What it all boils down to is the tension between a need to declare identity, a need to express what's precisely written on a specimen label, and a need to relate these to Collecting Events. The interplay among these three is not always a clean path & nor is it always synchronous with data entry. It often requires considerable effort using multiple, heterogeneous lines of evidence, to uncover the identity of a person behind the string of characters written on a label either as a member in a group or not. As such, and as has been noted here, entries in Agents risk ballooning into a spectacular mess...and likewise Collector Groups...if these processes & workflows are conflated & made synchronous. Choosing an Agent from a pick-list is an assertion, a declaration that you **know** who the person is that you chose. When you're uncertain in the choice, what do you do? Make a new Agent entry because you're constrained by the design of the software? How much research is necessary to be confident in the assertion?

So...

The question we need to answer is: Is Agents the home for clean, unique, verifiable entries of people (= identity) with aliases and external identifiers when known? And, is this the canonical source of relational entries in bundles that define group membership?

Here is what I suggest:

Agents _is_ that home for clean entries. However, there *must* be room for free-form text entry in Collecting Events for collectors if this field is meant to represent what is on a specimen label & might indeed be used to recreate physical specimen labels (hope that's a rare event). Likewise, this free-form field for the whole string of collector(s) or collector groups is what gets exported to GBIF or elsewhere. Doing otherwise injects a battery of nebulous assertions of identity. Attaching entries from Agents to a Collecting Event is a secondary, optional process that can be done long after a Collecting Event has been created...and sometimes never when there's utter uncertainty. But, it would be clear that what you're doing in that process is declaring identity against the verbatim string of collector(s).

What we'd still want to do however is enable rapid data entry of those "verbatim" collector strings in yet new Collecting Events, whether they be "Mrs. Smith's Grade 4 Class", "Such & Such Expedition", "Skevington & Lonsdale" or merely "J. Skevington". Could we then use all prior, unique "verbatim" entries across all Collecting Events as THE source for the collector pick-list? I bet we could because you're NOT declaring identity here, you're trying to faithfully represent what's on the label(s).

What we're missing in Collecting Events then is a home for free-form entry of "collectors".

**Comment by dshorthouse** [comment]
The TL;DR version to make into tickets if agreement:

- eliminate the ability to link Agents or create groups from the form when creating a new Collecting Event
- add a verbatim field for collector(s) in the above, make it editable in later forms
- add the ability to attach 1:many Agent(s) &/or create/attach a Group once a Collecting Event exists
- add a title field for the collecting event
- decide what will be searched upon & shown to a user when a Collecting Event will later need to be attached to a specimen record

**Comment by heathercole** [comment]
not clear if David's comments are to development team vs. managers, but would like to document that part of the reason to enable collector groups is to be able to re-use them. The notes above seem to indicate functionality that would require groups to be created each time needed. Managers need to be able to create groups of people, and re-use the groups. It should not be possible to edit group members after a group is created (that would be a different group).

**Comment by dshorthouse** [comment]
@heathercole Message was for everyone...but entirely possible that it's muddled. S'pose I'm seeking precision on the purpose. Is a group meant to circumscribe the identity of people for the purpose of ascribing credit OR is it meant to facilitate data entry as re-usable strings of characters? It's when we combine these distinct needs into one action (i.e. picking an agent to add to a group) that we get into trouble.

**Comment by heathercole** [comment]
I will add to agenda to discuss at next collection manager's meeting (next week)!

**Comment by cgendreau** [comment]
Thanks @dshorthouse , that explains very well the issues and a nice way to move forward.

**Comment by heathercole** [comment]
@cgendreau and @dshorthouse , unfortunately, based on David's notes on #97 there seems like a lot more going on here than I think can be effectively discussed with collection manager's at this time. I will certainly open the discussion, but unless you have specific questions that need specific answers, I think we will need to have more information on the intended functionality here. I can't discuss in the terms David has been using. If there are specific questions, please let me know, will gladly follow up with the managers.

**Comment by cgendreau** [comment]
This will be rolled back based on discussions in #92

**Comment by dshorthouse** [comment]
Seeking point of clarification: Do we need groups as first-class entities? Would they need linking to items outside their initial use? For example, if a group like `Skevington & Brooks` were created in the context of a collecting event, would this group ever need eventual linking to other things in DINA (eg publications? documents?) such that it becomes critical that the identity (= title) & composition (= agents) of this group be preserved?

**Comment by michellelocke** [comment]
I think what the CNC needs is a verbatim collecting field for entry of a text string that is entered exactly as it is on the label. If the entries could be indexed so that they autocomplete when typing (preferably in the form of a dropdown menu so that the user can start typing then select the one that matches quickly). This is a must have field.

It would be helpful to have the interpreted collector field as a link to agents and agent groups. When we initially talked about the idea of linkable agents the idea I had was that a user could look up an agent and see all of the things that agent has done in the database. So I could look up Jeff Skevington and see all of the specimens he collected, all of the identifications he has done, photos he has taken, records he has created, permits he has, etc. It seemed a good way to be able to ascribe many actions to a specific person. Maybe that idea has changed or is different in the eyes of others.

It is most important to have separate verbatim and interpreted fields so that it is clear which data is original and which is someone's interpretation. For legacy data this is of particular importance. I am open to how an interpreted field works, linking agents/groups and I think we all agree how the verbatim is to be implemented.

**Comment by dshorthouse** [comment]
Thanks @michellelocke. What this says to me is that Groups are not needed as first-class entities. They are conveniences relevant only to the context in which they are used. They accelerate data entry and as such, is just as useful to have a search index on the very same field you're entering data that uses all past entries. Enter it once (by anyone) and then everyone can then reuse it later in that very same field. That accelerates data entry of verbatim content. And so, there's no need to create & store groups (with all its complications of membership, identity, and ordering) because a group is not ever be used outside that data entry context in Collecting Event.

**Comment by heathercole** [comment]
@dshorthouse please note that there are other collections that are relevant to this requirement, and their input needs to be reviewed/incorporated also.  Additionally, the new system has to ensure forward compatibility to aggregators without additional efforts, would not make sense to develop in a way that would add a burden for sharing the data via manual exports or with aggregators like GBIF.

**Comment by dshorthouse** [comment]
@heathercole Yep, & thankfully someone in our midst is working with colleagues on an extension to Darwin Core to accommodate this and more https://github.com/tdwg/attribution/issues :)~. It's now available in IPTs in demo mode, manuscript is in prep w/ collections staff in a half-dozen countries that have kicked the tires, and we expect this to be in production soon-ish. We're the tugboats, pushing & pulling the ship from both ends.

**Comment by cgendreau** [comment]
As agreed on the last meeting we are now focusing on #92
