### ISSUE TITLE
Group - Definition and administration

### ISSUE THREAD

**Issue by rintoult** [AAFC-BICoE/dina-planning#83]
Dang - I had this all nicely written out a second ago and then I navigated away. Hopefully I can be as clear writing this out a second time. 

This is less of a bug report and more of an ask for information and teaching. 

With the dicusssion of ticket #67 and some questions from Heather my mind got churning on the "Group" entity in DINA. Here are my questions:

1. Who has admin rights on groups, how are they created?
2. What is the definition of a group, is it similar to how we applied it in SeqDB in that case CCFC the facility is a group that houses multiple collections
3. Where can we see a list of groups? 
4. How are agents/organisations related to groups can either of those things be the admin of a group?
5. In the object store we can filter on groups, will there be a secondary level available in the future where we might be able to also filter on collections when those become and entity?

Thank you for the informaiton, 
Tara

**Comment by rintoult** [comment]
Others who may be interested or have input in this. I think I am not doing this right for tagging people I will try harder next week. 

@heathercole @michellelocke @ron-reade @cgendreau @shannonasencio

**Comment by rintoult** [comment]
We just spent a long time talking about filtering on Groups in the SeqDB environment - almost all users required a multi-group filter, or some sort of toggle that allows them to make data visible/invisible as they are working through modules/pages. Once that design gets settled I will share it here.

**Comment by cgendreau** [comment]
Yes, the user interface is not ready yet that's why it is that obscure for the moment. The group filter is on its way so I will create a ticket for it so you can track it in the roadmap.

**Comment by cgendreau** [comment]
I added some definitions/concepts in the (new) User Manual:

https://github.com/AAFC-BICoE/dina-planning/blob/master/docs/UserManual.md

**Comment by heathercole** [comment]
what will be the permissions difference between admin and collection manager and between staff and students? or is that a topic that needs feedback from the managers?

**Comment by cgendreau** [comment]
The User Manual contains the current extend of permissions so (as today) there is currently no differences between admin and collection manager (same between student and staff).

**Comment by michellelocke** [comment]
It would seem to me that Group, as it currently stands, is equal to the Collection in a broad sense. This is a way to split up anything related to the CNC, from DAO, from CCFC, etc. It appears above that you want to make "groups" within your collection, so maybe sub-groups, within the CCFC. Is this correct? 

I would imagine that in the final product, we will not have access to each other's groups or collections, unless there is the need for cross-over. I imagine that Collections Managers will have administrative access at a Group level. If further division is needed, then it would seem that some type of sub-group would need to be created so that you can further sub-divide your collection, and administrate it all. I don't believe the CNC has a need for further division, but I can understand why it would be useful to other collections.

As for individual user permissions within a Group, maybe @heathercole this is something we need to discuss amongst our group, in terms of what types of things each level could do.

The CNC currently has three levels of overall permissions: administrator, manager and everyone else by default is a regular User. Admins have access to every specimen and every function. Managers have access to more functions than regular users. Specimen record and taxonomy record (in our taxonomy database and not discussed further) permissions are granted separately. Our Managers and Users have to be given permission (by Admins) to access the records in the database they need. Specimen record permissions are given based on either the user who controls the record or the taxon that the record has been determined as. I can give a user access to all of the Diptera specimens just by giving them access to edit that entire taxonomic group. I can also give a scientist access to all the records created by their student by giving then access to that person's records.

I can break down the permissions roles of the CNC DB further so that we can look at them if we have a further discussion on this amongst collection managers.

**Comment by cgendreau** [comment]
> I would imagine that in the final product, we will not have access to each other's groups or collections

Just to manage expectations, it will :) All records are viewable by all authenticated users.

**Comment by michellelocke** [comment]
> > I would imagine that in the final product, we will not have access to each other's groups or collections
> 
> Just to manage expectations, it will :) All records are viewable by all authenticated users.

That makes sense that all users could view all public records. I guess at one point it was talked about collections being completely separated off from one another but it doesn't seem we are operating on that model any longer.

**Comment by cgendreau** [comment]
Most of the answers are provided in the user manual mentioned above. I will create a ticket since the view where you can see the the users `url-of-the-test-server/dina-user/list` is not in the menu.
