### ISSUE TITLE
Add verbatim collectors field in collecting event

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#92]
GIVEN I have accessed DINA as a user (all roles)

WHEN I enter the value for `collectors`

THEN I must be able to enter the value as displayed on the label (in text)

AND the system assist me with existing values in the system

**Comment by heathercole** [comment]
it would be good if while trying to assign a collector that is not in the database, that you could do it on this form, instead of having to go somewhere else.

i am not clear about how when the re-order of associated agents is needed, for at least 2 collections, the order of agents is very important and should NOT be changeable once created. I think the feature may be useful when the record is being created, but a potential issue for editing. Not clear how this feature relates to agents which are groups with defined members.

**Comment by cgendreau** [comment]
Closing, verbatim collectors field added in collecting event.
