### ISSUE TITLE
Add basic support for agent aliases

### ISSUE THREAD

**Issue by cgendreau** [AAFC-BICoE/dina-planning#97]
GIVEN I have accessed DINA as a user

WHEN I enter or update an agent

THEN I should be able to enter an "alias" (alternative name for the same person)

**Comment by heathercole** [comment]
@michellelocke @cgendreau 
asking both of you for your perspective on this example.
There are 2 people. Paul Catling and his daughter Pauline (true story). They have both collected specimens accessioned in the herbarium. In the database, there are agents
Catling
Catling, P.M.
Catling, Paul
Catling, Paul M.
Catling, P.
Catling, Pauline

In the case of the agent "Catling, P", my first thought it to say that this cannot be used as an alias for Paul OR Pauline, because you would be able to "know" which "P. Catling" was relevant (@cgendreau  would that be correct from the database side?). BUT what if you did know, that for a particular collection, "P. Catling" was definitely Paul Catling (cause you were there too), @michellelocke would you then select the agent "Paul Catling" because you know it is him (data would be correct, but not match the label) OR would you select 'P. Catling' as that would match the label, but remain vague, as does not specifically identify which P. Catling was the collector. 

I think this is a combination of what is possible from the database side, then that influences how collections use it. 
(@shannonasencio just in case I am missing anything from the botany-data perspective)

**Comment by dshorthouse** [comment]
Can we tidy our use of terms? What you describe here @heathercole are what we'd more likely call agent strings as represented in the context where they are used and relevant. An entry in Agent is meant to represent a unique person. To be sure, there will be aliases in an Agent record, but as discussed elsewhere such as in #98 and #65, these would be used to help in the disambiguation process...the act of linking the item where the verbatim agent string is typed (eg collector P. Catling in Collecting Event, determiner Catling in determinations, photographer Pauline Catling in Multimedia, etc.) and the identity of the person as represented in Agents is a secondary process. Such disambiguation and linking absolutely requires context.

So, to re-iterate:

Any module where a person's name is written must be a verbatim field. Linking to an Agent entry is an additional step. These steps cannot be collapsed into a single action that draws-in content from the Agent module because you'd conflate display with disambiguation as you've outlined here.

**Comment by heathercole** [comment]
speaking of terms, I definitely do not fully understand many of the terms and relationships you @dshorthouse are commenting about here. I think for this topic, WP3 will have to present either an example of the data fields or a demo of the user interface. Else some more time must be taken to describe the final product functionality so that collection managers can indicate if it will meet their requirements.

My own understanding of "verbatim" fields is that they require the user to enter all the data manually. That may not be the case. [part] of the requirements for the agent-related fields is that when adding people-names (eg. collectors/determiners/catalogers) the names can be re-used and not entered manually each time.

**Comment by dshorthouse** [comment]
> My own understanding of "verbatim" fields is that they require the user to enter all the data manually. That may not be the case. [part] of the requirements for the agent-related fields is that when adding people-names (eg. collectors/determiners/catalogers) the names can be re-used and not entered manually each time.
 
It DOES mean that, but it does not mean you can't have search/autocomplete on that field. It's just that there is NO direct link made between the content in that verbatim field and an entry in Agent. We could be clever & attempt to make that link as part of the UI, but such a link would sit alongside the verbatim entry and you should then have the ability to remove that link and make it point to the correct Agent entry is the guess was incorrect without editing the verbatim content.

**Comment by heathercole** [comment]
I can discuss functionality with the managers, but would possibly be more clear if these issues focused on describing what the user would experience, rather than including behind-the-scenes functionality. Certainly how data fields are structured and related to each other are part of what managers need to understand, but I don't think at this stage we need to understand the detailed back-end.

**Comment by dshorthouse** [comment]
Fair enough. The TL;DR version:

Two fields where there are people names: Verbatim, Agent.

Former stored as text, latter is a relational link. Both presented as input boxes. Both have autocomplete. Former autocomplete operates off all "agent strings" used in that module. So, would initially be a non-result when nothing yet added to the search index & so would be nothing more than free-form typing. Latter is a text field that autocompletes against an Agent entry & when person chosen, input box changes to a string display with an icon to remove it & then recreate it. Latter "could" be attempted as part of the js UI but the user would have ability to remove the link and correct it without editing the verbatim entry.

**Comment by cgendreau** [comment]
Can we make it even more general:

* add a verbatim field for collector(s) (with the autocomplete described above)
* add the optional ability to link 1:many Agent(s)

**Comment by heathercole** [comment]
would the functionality described above mean that every agent would have to be manually typed "the first time". This would not be acceptable, as would not be a good use of human time for agents already maintained/entered in the database.

**Comment by dshorthouse** [comment]
@heathercole Migration of legacy data as unique Agent entries & oodles of agent strings into the modules where they are expressed would cover that.

**Comment by heathercole** [comment]
@dshorthouse  do you mean [all existing agents will be available in the auto-complete and won't have to be entered manually]

**Comment by dshorthouse** [comment]
@cgendreau Also: ability to remove link and recreate a different one for any/all of the Agent links. Added enhancement in future phase would be auto-linking of Agent on blur from verbatim.

**Comment by dshorthouse** [comment]
@heathercole There are 2 distinct autocompletes here because there are 2 distinct actions that we need to disentangle & not conflate. One for the verbatim drawn from other verbatim values...the "save yourself some typing but still verbatim" and one for the link to Agent...the "this is exactly who I mean in verbatim". But yes, both field and link(s) would be populated from legacy data.

**Comment by cgendreau** [comment]
So this ticket helped to move forward on #92 and #98 but can probably be closed now.

**Comment by michellelocke** [comment]
I know this is closed now but I think I agree with everything @dshorthouse said. We would require two fields, a verbatim field where the data is entered directly from the label, as is, and an interpreted agents field, where the data would not need to match the verbatim. So P. Catling in the verbatim could be tagged as Paul Catling in the interpreted agents field if you knew it was Paul instead of Pauline.

As agents will be interpreted, it may not always be appropriate for students/volunteers to do and may be a job that collections staff need to go back and fix. Also, I would not expect the legacy data to be tagged and would expect that to be a data cleaning job that gets worked on by collections staff over time. Presumably we could find easier ways to do this like searching the verbatim collector field for Vockeroth and then tagging all of those records with the agent J. Richard Vockeroth.

I don't care if I have to enter all of the names in once. We already do that. Our only autocomplete currently is if the web browser remembers what you are typing and autocompletes. Our database does not do that. It would be fantastic if DINA autocompletes/references what is already in that field.

Anyways, that's my two cents. I think I agree with where DINA is heading in regards to this.
